name: Terraform-Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action to Execute'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    name: Deploy Infrastructure
    uses: driveops-surya/devops-reusable-workflows/.github/workflows/environment-stages.yml
    with:
      action: ${{ github.event.inputs.action || 'plan' }}
      environment: ${{ github.event.inputs.environment || 'dev' }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
